from fpdf import FPDF
import streamlit as st

class JobReportPDF(FPDF):
    def header(self):
        # Arial bold 15
        self.set_font("helvetica", "B", 15)
        # Title
        self.cell(0, 10, "Job Search & Application Report", new_x="LMARGIN", new_y="NEXT", align="C")
        # Subtitle
        self.set_font("helvetica", "I", 10)
        self.cell(0, 8, "Generated by Job Search AI Agent", new_x="LMARGIN", new_y="NEXT", align="C")
        # Line break
        self.ln(5)
        # Draw header line
        self.line(10, 30, 200, 30)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font("helvetica", "I", 8)
        # Page number
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def generate_pdf_report(jobs):
    """
    Generates a clean PDF document containing a list of job search results or tracked applications.
    Returns the raw PDF bytes.
    """
    try:
        pdf = JobReportPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_font("helvetica", "", 10)
        
        if not jobs:
            pdf.cell(0, 10, "No jobs to report.", new_x="LMARGIN", new_y="NEXT")
            # output() in fpdf2 returns bytearray
            return bytes(pdf.output())
            
        for idx, job in enumerate(jobs):
            title = job.get("job_title", "N/A")
            company = job.get("employer_name", "N/A")
            location = job.get("job_city") or job.get("job_state") or "N/A"
            
            salary = "Not disclosed"
            if job.get("job_min_salary") and job.get("job_max_salary"):
                salary = f"{job['job_min_salary']} - {job['job_max_salary']}"
                
            emp_type = job.get("job_employment_type", "N/A")
            # Handle list if employment types is a list
            if isinstance(emp_type, list):
                emp_type = ", ".join(emp_type)
                
            apply_link = job.get("job_apply_link") or "N/A"
            status = job.get("status") # If from application tracker
            
            # Job Header
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(0, 8, f"{idx+1}. {title} @ {company}", new_x="LMARGIN", new_y="NEXT")
            
            # Job Details
            pdf.set_font("helvetica", "", 10)
            details_str = f"Location: {location} | Employment Type: {emp_type} | Salary: {salary}"
            if status:
                details_str += f" | Tracker Status: {status}"
            pdf.cell(0, 6, details_str, new_x="LMARGIN", new_y="NEXT")
            
            # Apply Link
            if apply_link and apply_link != "N/A":
                pdf.write(6, "Apply Link: ")
                pdf.set_text_color(0, 0, 255)
                pdf.set_font("helvetica", "U", 10)
                pdf.write(6, apply_link, apply_link)
                pdf.set_text_color(0, 0, 0)
                pdf.set_font("helvetica", "", 10)
                pdf.ln(8)
            else:
                pdf.ln(4)
                
            # Divider line
            curr_y = pdf.get_y()
            pdf.line(10, curr_y, 200, curr_y)
            pdf.ln(5)
            
        return bytes(pdf.output())
    except Exception as e:
        st.error(f"⚠️ PDF Generation Failed: {e}")
        return None
